# Generated by Django 4.0 on 2022-11-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_remove_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_company',
            field=models.IntegerField(choices=[(1, 'DPD'), (2, 'Fedex'), (3, 'UPS')], null=True),
        ),
    ]
