# Generated by Django 4.0 on 2022-11-17 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_alter_order_delivery_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=6, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Invalid postal code')]),
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
